### PR TITLE
[coq] Adapt to zarith, Coq's PR coq/coq#8743

### PR DESCRIPTION
**Pull request by ejgallego**

### CODE REVIEW

**Review by maximedenes — APPROVED** [review]

**Comment by maximedenes** [comment]
@ejgallego Apparently the build failed. I didn't look at the failure.

**Comment by liyishuai** [comment]
Depends on coq/opam-coq-archive#1410

**Comment by RalfJung** [comment]
The commit message references the wrong Coq PR I think? It references a draft; https://github.com/coq/coq/pull/11742 is the PR that landed.

**Comment by SkySkimmer** [comment]
I guess the nix file needs a dep on zarith
No clue how the docker setup works

**Comment by ppedrot** [comment]
Shouldn't this be merged now?

**Comment by maximedenes** [comment]
> Shouldn't this be merged now?

The build failed, didn't it?

**Comment by liyishuai** [comment]
The failing build was before merging coq/opam-coq-archive#1410. Try restarting.

**Comment by liyishuai** [comment]
Ehh we might need to wait for Cachix and Docker to update the images and include `zarith` package.

**Comment by erikmd** [comment]
@liyishuai indeed. Regarding the Docker images: I'd propose to add zarith (and the APT package libgmp-dev) in the base images `coqorg/base:*` (this is already the case for dune, for example).
If no one objects, I'll rebuild the images accordingly ASAP.
(Otherwise, the other solution would be to only install `zarith` in `coqorg/coq:dev`)

**Comment by erikmd** [comment]
Hi, the `coqorg/base` images are ready as well as `coqorg/coq:*`, except `coqorg/coq:dev`, because there is actually a kind of deadlock: this PR #44 does not compile because `coqorg/coq:dev` must be rebuilt with `zarith` inside, but `coqorg/coq:dev` [does not compile](https://gitlab.com/coq-community/docker-coq/-/jobs/710411879) because it incorporates bignums master… (and not bignums from #44).
So two solutions:
1. either we merge #44 as is,
2. or we refactor beforehand bignums' CI, e.g. to rely on the mere `coqorg/base` Docker image (to the expense of slower bignums CI builds)

**Comment by liyishuai** [comment]
I'd prefer merging as is. CI should not block a merge that fixes the CI itself.

**Comment by maximedenes** [comment]
> CI should not block a merge that fixes the CI itself.

Where can we see that it does fix the CI?

**Comment by maximedenes** [comment]
Ah, I see, bignums is missing some kind of overlay systems for its dependencies. Ok, let's merge and see. It's already broken anyway, IIUC.

**Comment by SkySkimmer** [comment]
The nix test should be fixable independently of the docker stuff

**Comment by erikmd** [comment]
Hi,
Thanks @maximedenes!, so the `coqorg/coq:dev` build is on-going:
https://gitlab.com/coq-community/docker-coq/-/pipelines/183766132

For the nix test, there might be another blocking issue (I mean, beyond the fact #44 is a non-backward-compatible patch),
cf. the CI failure in https://github.com/coq/bignums/pull/46 (maybe @Zimmi48 could have another look at #46)

**Comment by erikmd** [comment]
just FYI, the docker-based CI is now OK in master: https://travis-ci.com/github/coq/bignums/jobs/379399407

**Pull request merged**
