### PR TITLE
[CI] Simplify build-coq-bignums.yml using upcoming docker-coq-action 1.2.0

### PR DESCRIPTION
**Pull request by erikmd**
* Testing https://github.com/coq-community/docker-coq-action/pull/33
* To be merged later on (only in draft mode for now)

### CODE REVIEW

**Comment by Zimmi48** [comment]
Should probably be changed to use `OPAMWITHTEST`.

**Comment by erikmd** [comment]
@Zimmi48 feel free to assign/merge this PR, now relying on the new docker-coq-action v1 (= v1.2.0)

**Review by Zimmi48 — APPROVED** [review]
LGTM
The next step will be to improve the coq-community templates to support the `OPAMWITHTEST` use case :wink:

**Comment by erikmd** [comment]
Thanks @Zimmi48 

> The next step will be to improve the coq-community templates to support the OPAMWITHTEST use case.

Exactly! I was precisely thinking about this as well :)

**Pull request merged**
