### PR TITLE
Fix Nix build on Travis CI (backport for v8.12)

### PR DESCRIPTION
**Pull request by erikmd**

### CODE REVIEW

**Comment by erikmd** [comment]
Hi @vbgl, I've just realized a Coq 8.12 test was missing for this second PR.
Now fixed − and let's wait for the CI :)

**Comment by erikmd** [comment]
CI is green :heavy_check_mark:

**Comment by vbgl** [comment]
Thanks.

Is someone willing to put a tag for 8.12?

**Comment by erikmd** [comment]
Thanks @vbgl for the merge! regarding the 8.12.0 release of bignums, maybe there's no hurry and we can just wait for the Coq release itself? cf. the question I had asked in this thread: https://github.com/coq/coq/issues/11157#issuecomment-646139730

**Pull request merged**
