### PR TITLE
Remove explicit open API for compatibility with 8.7 and 8.8.

### PR DESCRIPTION
**Pull request by Zimmi48**
And regenerate Makefile from most recent version of coq_makefile.

This makes the plugin compatible with branch master with PR coq/coq#963
and with branch v8.7 after merge of PR coq/coq#945.

### CODE REVIEW

**Comment by silene** [comment]
Was it actually tested? The fact that the patch causes the files to no longer provide the list of files to compile does not bode well.

**Comment by Zimmi48** [comment]
That's a very relevant remark @silene. The Makefile was auto-generated but by the new coq_makefile, thus there is a new file Makefile.conf which I had forgotten to commit, among the mass of compilation outputs not listed in .gitignore.

And yes, it was tested against these two versions  (on my own machine).

**Comment by Zimmi48** [comment]
Correction: this works with both branches only if `Makefile.conf` is *not* committed  (and thus can be removed by `git clean -dfx`). It forces coq_makefile to regenerate the `Makefile` when running `make`, and thus adapt it to the current version being used.

**Comment by silene** [comment]
No way! You are committing to a repository a file (`Makefile`) that will be overwritten as soon as the user types `make`. This cannot be a good thing.

**Comment by Zimmi48** [comment]
It is overwritten only if the user compiles the plugin with a different version of Coq that the one who was used to generate it. And this is because between Coq 8.7 and Coq 8.8, there is a change in what this Makefile must contain. If you see a better solution which would be backward compatible (avoid maintaining a different branch for 8.7 and 8.8), feel free to propose it.

**Comment by silene** [comment]
> It is overwritten only if the user compiles the plugin with a different version of Coq

Let me correct that. It is always overwritten! It just happens that if the user happens to use exactly the same version of Coq as yours, the overwritten file is identical. And that is only assuming it worked in the first face, since your path to `coq_makefile` (or its absence thereof) might not be the one used by the user. (It probably qualifies as a bug that the generated `Makefile` does not use `COQMKFILE` and thus does not respect `COQBIN` @gares ).

> feel free to propose it.

Why not having an almost empty `Makefile` whose only purpose is to call `coq_makefile -f Make -o Makefile.coq`, as done in several contribs, e.g. MathClasses.

**Comment by Zimmi48** [comment]
> Why not having an almost empty Makefile whose only purpose is to call coq_makefile -f Make -o Makefile.coq, as done in several contribs, e.g. MathClasses.

Indeed, that's much better. I've just updated the PR. (And I've tested again against both versions to confirm it still works.)

Do you have merge rights on this repository? If yes, can you merge the PR?

**Comment by silene** [comment]
> Do you have merge rights on this repository?

It seems I do. No idea who does or does not have rights.

**Comment by Zimmi48** [comment]
> No idea who does or does not have rights.

I suppose you have because you are an admin of the coq organization.

**Pull request merged**
