### PR TITLE
Add missing Dune dependency to opam file.

### PR DESCRIPTION
**Pull request by Zimmi48**
See https://github.com/coq/opam-coq-archive/pull/885#discussion_r317769466

### CODE REVIEW

**Comment by ejgallego** [comment]
By the way @zimmi48 , dune can generate opam files since 1.10 I believe, it would be great if we could provide feedback on this from the point of view of coq packages .

**Comment by anton-trunov** [comment]
@ejgallego This is cool! Is it possible to add dependency version constraints to generated opam files? If it, where do we put e.g. the version ranges?

**Comment by Zimmi48** [comment]
@anton-trunov It is, and it is documented: https://dune.readthedocs.io/en/stable/opam.html#generating-opam-files

**Comment by anton-trunov** [comment]
@Zimmi48 This looks great, thank you!

**Comment by ejgallego** [comment]
One possible line of feedback is to let Dune devs know what info is missing so for example Nix recipes could be also generated.

**Pull request merged**
