### PR TITLE
Disable native compute for dune (unbreak the bench)

### PR DESCRIPTION
**Pull request by SkySkimmer**
Close coq/coq-bench#83

### CODE REVIEW

**Comment by ppedrot** [comment]
So *that*'s the reason a few packages are broken -_-

**Comment by Zimmi48** [comment]
Reverts part of #38, more precisely part of 3539b53 (cc @proux01 @erikmd).
As for the other part of 3539b53, it probably is responsible for #39.

**Comment by proux01** [comment]
Sorry, I'm obviously the one responsible for that and I fully agree with this patch.

That being said, as pointed out by @ejgallego in 
https://github.com/coq/coq-bench/issues/83#issuecomment-608992792 bignums should not be built with dune for now so maybe fully removing this dune file would be safer?

**Comment by ejgallego** [comment]
Bignums is installed using opam in the bench, so why the `dune` file is used?

**Comment by ejgallego** [comment]
@proux01 note tho that we purposely disable native on the bench as it would introduce a lot of noise for example when testing different OCaml versions.

So this PR seems like the right thing to do.

**Comment by proux01** [comment]
Sorry, my previous comment was in the wrong topic
> Maybe because https://github.com/coq/opam-coq-archive/blob/master/extra-dev/packages/coq-bignums/coq-bignums.dev/opam

> I'm opening a PR on opam-coq-archive.

So should we rather keep dune in the OPAM file for coq-bignums.dev ?

**Comment by proux01** [comment]
Ok, closing https://github.com/coq/opam-coq-archive/pull/1237 then.

**Comment by ejgallego** [comment]
> So should we rather keep dune in the OPAM file for coq-bignums.dev ?

We should have a switch to enable native in the bench; I'll open an issue and see how we track that.

IMO it is safer for now not to enable native yet.

**Pull request merged**
