### PR TITLE
Add docker-coq CI for v8.13

### PR DESCRIPTION
**Pull request by erikmd**

### CODE REVIEW

**Comment by erikmd** [comment]
As this "chore" PR is trivial and has a green CI, let me merge it now…

**Comment by Zimmi48** [comment]
@erikmd This was the last PR where CI ran (recent PRs opened on bignums do not trigger CI, nor do commits pushed to master). Any idea why this could be?

**Comment by erikmd** [comment]
@Zimmi48 yes, I experienced this in another repo as well: it's not a bug but a (new) feature → see this screenshot of [that page](https://github.com/coq/bignums/actions/workflows/build-coq-bignums.yml):

2021-07-08_20-26-22_Screenshot_bignums

To sum up: for each workflow that involves the feature
```
on:
  …
  schedule:
      - cron: '0 4 * * *'
```
there's the risk that the scheduled workflow (as well as any related runs for PRs/branches) is disabled after 60 days.

For the time being, I clicked on the button `Enable workflow`, so that should be OK now.

**Comment by Zimmi48** [comment]
Thanks for the explanation! I find this behavior super weird (the workflow was disabled but didn't start again when there was activity). I will send feedback to GitHub about this.

**Pull request merged**
