### PR TITLE
[build] Add Dune support.

### PR DESCRIPTION
**Pull request by ejgallego**
Nothing remarkable other than a slight code reorganization.

### CODE REVIEW

**Comment by ejgallego** [comment]
I'll merge myself in absence of complains I guess.

**Comment by gares** [comment]
Looks like ci only tests coqmakefile. And gives a ton of nix specific warnings about non elf files.

**Comment by Zimmi48** [comment]
>And gives a ton of nix specific warnings about non elf files.

Sorry about that: I don't know what we can do about it. I think we already asked @vbgl, but he may still know more and have an idea.

(Anyway, that's unrelated to this PR.)

**Comment by ejgallego** [comment]
I'm afraid I'll need help with the CI as I am not a Nix user [yet]

**Comment by Zimmi48** [comment]
I'm working on it.

**Comment by Zimmi48** [comment]
I'll wait for Dune's 1.0 support for Coq to move the `default.nix` file to Dune. At that point, we should be able to just remove the legacy build system. In the meantime, coq_makefile is tested through Nix and Dune through opam, following the CI template provided by coq-community.

@ejgallego Feel free to merge this yourself.

**Comment by Zimmi48** [comment]
Given the uselessness of the current README, I'll also push a README based on the coq-community template. But feel free to merge without waiting for CI. It has already passed once ;-)

**Comment by ejgallego** [comment]
Very nice, thanks a lot @Zimmi48 .

**Pull request merged**
