### PR TITLE
compatibility with Coq PR #14045

### PR DESCRIPTION
**Pull request by fajb**
zify is more aggressive and generalises  the theorem
`0 < a -> 0 < b -> 0 < a ^ b.`

This PR repairs the few impacted proofs.

### CODE REVIEW

**Comment by fajb** [comment]
@thery could you have a look?

**Review by thery — APPROVED** [review]
Fine

**Comment by thery** [comment]
@fajb Do you want me to merge?

**Comment by fajb** [comment]
> @fajb Do you want me to merge?

Yes. Thanks.

**Comment by thery** [comment]
@coqbot: merge now

**Comment by thery** [comment]
opps we have to do it manually here I suppose

**Comment by thery** [comment]
but I don't have the merge right

**Comment by fajb** [comment]
It is the right repo, right? Or was it moved elsewhere?

**Comment by thery** [comment]
let's ask @Zimmi48

**Comment by silene** [comment]
@thery I have given you access.

**Pull request merged**
